"""Explicit immutable value types approved for Intelligence History."""

from dataclasses import is_dataclass
from typing import Any

from dip.intelligence.modules.hidden_gems import HiddenGemCandidate
from dip.intelligence.modules.historical_intelligence import (
    HistoricalComparison,
    HistoricalReleaseChange,
    HistoricalReleaseIdentity,
    HistoricalSnapshotInfo,
)
from dip.decision_intelligence import (
    ActivityIntensityComponent,
    ActivityIntensityThresholds,
    AppearancePersistenceContext,
    EvidenceCoverageComponent,
    FactualSupportingContext,
    ListingPersistenceContext,
    MarketplaceMomentumDiagnostic,
    MarketplaceMomentumOutput,
    MarketplaceMomentumSummary,
    MomentumComponents,
    PriceDirectionComponent,
    ReleaseMomentum,
    SourceProvenance,
    SupplyDirectionComponent,
    AppearanceContinuityComponent,
    AppearanceContinuityThresholds,
    ChangeStabilityComponent,
    ChangeStabilityThresholds,
    ListingPersistenceComponent,
    ListingPersistenceFacts,
    ListingPersistenceThresholds,
    MarketplaceStabilityDiagnostic,
    MarketplaceStabilityOutput,
    MarketplaceStabilitySummary,
    ReleaseStability,
    StabilityComponents,
    StabilitySourceProvenance,
    AppearanceScarcityComponent,
    AppearanceScarcityThresholds,
    AvailabilityThresholds,
    ListingPersistenceScarcityComponent,
    ListingScarcityThresholds,
    MarketplaceScarcityDiagnostic,
    MarketplaceScarcityOutput,
    MarketplaceScarcitySummary,
    ObservedAvailabilityComponent,
    ReleaseScarcity,
    ScarcityComponents,
    ScarcitySourceProvenance,
    ScarcitySupplyContext,
    MarketplaceOpportunityDiagnostic,
    MarketplaceOpportunityOutput,
    MarketplaceOpportunitySummary,
    OpportunityDimension,
    OpportunityDimensions,
    OpportunityRuleConfiguration,
    OpportunitySourceProvenance,
    ReleaseOpportunity,
)
from dip.marketplace_intelligence.models import MarketplaceDiagnostic, MarketplaceMoney
from dip.marketplace_intelligence.price_changes import (
    ListingPriceChange,
    PriceChangeDelta,
    PriceChangesOutput,
    PriceChangesSnapshotReference,
    PriceChangesSummary,
    ReleasePriceChange,
)
from dip.marketplace_intelligence.supply_changes import (
    ReleaseSupplyChange,
    SupplyChangesOutput,
    SupplyChangesSnapshotReference,
    SupplyChangesSummary,
)
from dip.marketplace_intelligence.rare_appearances import (
    RareAppearance,
    RareAppearanceSnapshotReference,
    RareAppearancesOutput,
    RareAppearancesSummary,
)
from dip.marketplace_intelligence.marketplace_activity import (
    MarketplaceActivityObservationReference,
    MarketplaceActivityOutput,
    MarketplaceActivitySummary,
    ReleaseActivity,
)
from dip.marketplace_intelligence.listing_lifecycle import (
    ListingLifecycle,
    ListingLifecycleOutput,
    ListingLifecycleSnapshotReference,
    ListingLifecycleSummary,
)
from dip.marketplace_intelligence.weekend_listings import (
    WeekendListingCandidate,
    WeekendListingsOutput,
    WeekendWindow,
)
from dip.portfolio_intelligence import (
    PortfolioConcentrationFacts,
    PortfolioDistribution,
    PortfolioDistributionEntry,
    PortfolioOverviewDiagnostic,
    PortfolioOverviewOutput,
    PortfolioOverviewRuleConfiguration,
    PortfolioOverviewSummary,
    PortfolioOwnershipSummary,
    PortfolioReleaseOverview,
    PortfolioSourceProvenance,
    PortfolioDimensionDistribution,
    PortfolioDistributionConcentration,
    PortfolioDistributionDiagnostic,
    PortfolioCategoryDistributionEntry,
    PortfolioDistributionOutput,
    PortfolioDistributionOwnershipSummary,
    PortfolioDistributionProvenance,
    PortfolioDistributionRuleConfiguration,
    PortfolioDistributionSummary,
    PortfolioReleaseDistributionDetail,
    PortfolioCategoryContribution,
    PortfolioConcentrationDiagnostic,
    PortfolioConcentrationDifference,
    PortfolioConcentrationMetricSet,
    PortfolioConcentrationOutput,
    PortfolioConcentrationProvenance,
    PortfolioConcentrationRuleConfiguration,
    PortfolioConcentrationSummary,
    PortfolioDimensionConcentration,
    PortfolioTopNConcentration,
)
from dip.portfolio_decision_intelligence import (
    PortfolioCategoryAlignment,
    PortfolioDimensionAlignment,
    PortfolioOpportunityAlignmentDiagnostic,
    PortfolioOpportunityAlignmentOutput,
    PortfolioOpportunityAlignmentProvenance,
    PortfolioOpportunityAlignmentRuleConfiguration,
    PortfolioOpportunityAlignmentSummary,
    PortfolioOpportunityBreadth,
    PortfolioOpportunityMappingEntry,
)
from dip.historical_intelligence import (
    CategoricalTransition,
    CollectionTransition,
    ComparisonProvenance,
    ComparisonRuleConfiguration,
    ComparisonSummary,
    IntelligenceChangeAnalysisDiagnostic,
    IntelligenceComparisonOutput,
    MetricTransition,
    IntelligenceCategoricalTrend,
    IntelligenceDimensionTrend,
    IntelligenceNumericMetricTrend,
    IntelligencePresenceTrend,
    IntelligencePresenceItemTrend,
    IntelligenceStateTransitionFrequency,
    IntelligenceTrendAnalysisOutput,
    IntelligenceTrendAnalysisSummary,
    IntelligenceTrendDiagnostic,
    IntelligenceTrendProvenance,
    IntelligenceTrendRuleConfiguration,
)


APPROVED_DATACLASS_TYPES: dict[str, type[Any]] = {
    f"{value_type.__module__}.{value_type.__qualname__}": value_type
    for value_type in (
        HiddenGemCandidate,
        HistoricalComparison,
        HistoricalReleaseChange,
        HistoricalReleaseIdentity,
        HistoricalSnapshotInfo,
        ActivityIntensityComponent,
        ActivityIntensityThresholds,
        AppearancePersistenceContext,
        EvidenceCoverageComponent,
        FactualSupportingContext,
        ListingPersistenceContext,
        MarketplaceMomentumDiagnostic,
        MarketplaceMomentumOutput,
        MarketplaceMomentumSummary,
        MomentumComponents,
        PriceDirectionComponent,
        ReleaseMomentum,
        SourceProvenance,
        SupplyDirectionComponent,
        AppearanceContinuityComponent,
        AppearanceContinuityThresholds,
        ChangeStabilityComponent,
        ChangeStabilityThresholds,
        ListingPersistenceComponent,
        ListingPersistenceFacts,
        ListingPersistenceThresholds,
        MarketplaceStabilityDiagnostic,
        MarketplaceStabilityOutput,
        MarketplaceStabilitySummary,
        ReleaseStability,
        StabilityComponents,
        StabilitySourceProvenance,
        AppearanceScarcityComponent,
        AppearanceScarcityThresholds,
        AvailabilityThresholds,
        ListingPersistenceScarcityComponent,
        ListingScarcityThresholds,
        MarketplaceScarcityDiagnostic,
        MarketplaceScarcityOutput,
        MarketplaceScarcitySummary,
        ObservedAvailabilityComponent,
        ReleaseScarcity,
        ScarcityComponents,
        ScarcitySourceProvenance,
        ScarcitySupplyContext,
        MarketplaceOpportunityDiagnostic,
        MarketplaceOpportunityOutput,
        MarketplaceOpportunitySummary,
        OpportunityDimension,
        OpportunityDimensions,
        OpportunityRuleConfiguration,
        OpportunitySourceProvenance,
        ReleaseOpportunity,
        MarketplaceDiagnostic,
        MarketplaceMoney,
        ListingPriceChange,
        PriceChangeDelta,
        PriceChangesOutput,
        PriceChangesSnapshotReference,
        PriceChangesSummary,
        ReleasePriceChange,
        ReleaseSupplyChange,
        SupplyChangesOutput,
        SupplyChangesSnapshotReference,
        SupplyChangesSummary,
        RareAppearance,
        RareAppearanceSnapshotReference,
        RareAppearancesOutput,
        RareAppearancesSummary,
        MarketplaceActivityObservationReference,
        MarketplaceActivityOutput,
        MarketplaceActivitySummary,
        ReleaseActivity,
        ListingLifecycle,
        ListingLifecycleOutput,
        ListingLifecycleSnapshotReference,
        ListingLifecycleSummary,
        WeekendListingCandidate,
        WeekendListingsOutput,
        WeekendWindow,
        PortfolioConcentrationFacts,
        PortfolioDistribution,
        PortfolioDistributionEntry,
        PortfolioOverviewDiagnostic,
        PortfolioOverviewOutput,
        PortfolioOverviewRuleConfiguration,
        PortfolioOverviewSummary,
        PortfolioOwnershipSummary,
        PortfolioReleaseOverview,
        PortfolioSourceProvenance,
        PortfolioDimensionDistribution,
        PortfolioDistributionConcentration,
        PortfolioDistributionDiagnostic,
        PortfolioCategoryDistributionEntry,
        PortfolioDistributionOutput,
        PortfolioDistributionOwnershipSummary,
        PortfolioDistributionProvenance,
        PortfolioDistributionRuleConfiguration,
        PortfolioDistributionSummary,
        PortfolioReleaseDistributionDetail,
        PortfolioCategoryContribution,
        PortfolioConcentrationDiagnostic,
        PortfolioConcentrationDifference,
        PortfolioConcentrationMetricSet,
        PortfolioConcentrationOutput,
        PortfolioConcentrationProvenance,
        PortfolioConcentrationRuleConfiguration,
        PortfolioConcentrationSummary,
        PortfolioDimensionConcentration,
        PortfolioTopNConcentration,
        PortfolioCategoryAlignment,
        PortfolioDimensionAlignment,
        PortfolioOpportunityAlignmentDiagnostic,
        PortfolioOpportunityAlignmentOutput,
        PortfolioOpportunityAlignmentProvenance,
        PortfolioOpportunityAlignmentRuleConfiguration,
        PortfolioOpportunityAlignmentSummary,
        PortfolioOpportunityBreadth,
        PortfolioOpportunityMappingEntry,
        CategoricalTransition,
        CollectionTransition,
        ComparisonProvenance,
        ComparisonRuleConfiguration,
        ComparisonSummary,
        IntelligenceChangeAnalysisDiagnostic,
        IntelligenceComparisonOutput,
        MetricTransition,
        IntelligenceCategoricalTrend,
        IntelligenceDimensionTrend,
        IntelligenceNumericMetricTrend,
        IntelligencePresenceTrend,
        IntelligencePresenceItemTrend,
        IntelligenceStateTransitionFrequency,
        IntelligenceTrendAnalysisOutput,
        IntelligenceTrendAnalysisSummary,
        IntelligenceTrendDiagnostic,
        IntelligenceTrendProvenance,
        IntelligenceTrendRuleConfiguration,
    )
}


def approved_dataclass_name(value: Any) -> str | None:
    """Return the stable registry name for an approved dataclass value."""

    value_type = type(value)
    name = f"{value_type.__module__}.{value_type.__qualname__}"
    if is_dataclass(value) and APPROVED_DATACLASS_TYPES.get(name) is value_type:
        return name
    return None
