"""Immutable Marketplace Intelligence domain and serialization contracts."""

from .models import (
    MarketplaceDataStatus,
    MarketplaceDiagnostic,
    MarketplaceDiagnosticSeverity,
    MarketplaceDomainError,
    MarketplaceExecutionContext,
    MarketplaceListingObservation,
    MarketplaceModuleResult,
    MarketplaceMoney,
    MarketplaceReleaseObservation,
    MarketplaceSnapshot,
)
from .serialization import (
    JsonValue,
    MARKETPLACE_SCHEMA_VERSION,
    MarketplaceDeserializationError,
    MarketplaceSerializationError,
    dumps_marketplace_module_result,
    dumps_marketplace_snapshot,
    loads_marketplace_module_result,
    loads_marketplace_snapshot,
    marketplace_module_result_from_dict,
    marketplace_module_result_to_dict,
    marketplace_snapshot_from_dict,
    marketplace_snapshot_to_dict,
)

__all__ = [
    "JsonValue",
    "MARKETPLACE_SCHEMA_VERSION",
    "MarketplaceDataStatus",
    "MarketplaceDeserializationError",
    "MarketplaceDiagnostic",
    "MarketplaceDiagnosticSeverity",
    "MarketplaceDomainError",
    "MarketplaceExecutionContext",
    "MarketplaceListingObservation",
    "MarketplaceModuleResult",
    "MarketplaceMoney",
    "MarketplaceReleaseObservation",
    "MarketplaceSerializationError",
    "MarketplaceSnapshot",
    "dumps_marketplace_module_result",
    "dumps_marketplace_snapshot",
    "loads_marketplace_module_result",
    "loads_marketplace_snapshot",
    "marketplace_module_result_from_dict",
    "marketplace_module_result_to_dict",
    "marketplace_snapshot_from_dict",
    "marketplace_snapshot_to_dict",
]
